version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@1.1.5
  heroku: circleci/heroku@2.0.0
jobs:
  build:
    docker:
    - image: cimg/node:16.10
    steps:
    - checkout
    - node/install-packages:
        pkg-manager: npm
    - run:
        echo "Install dependencies"
        npm install
  test:
    docker:
    - image: cimg/node:16.10
    steps:
    - checkout
    - node/install-packages:
        pkg-manager: npm
    - run:
        echo "Running tests"
        npm run test
  deploy:
    docker:
    - image: cimg/node:16.10
    steps:
    - setup_remote_docker
    - heroku/install
    - checkout
    - run:
        name: Heroku Container Push
        command:
          heroku container:login
          heroku stack:set container -a fazlieramdan-su-devops
          heroku container:push web -a fazlieramdan-su-devops
          heroku container:release web -a fazlieramdan-su-devops


workflows:
  simple_workflow:
    jobs:
    - build
    - test:
        requires:
        - build
    - deploy:
        requires:
        - test
        