version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
  snyk: snyk/snyk@1.5.0
jobs:
  build:
    docker:
    - image: cimg/node:16.10
    steps:
    - checkout
    - node/install-packages:
        pkg-manager: npm
    - run:
        echo "Install dependencies"
        npm install
  test:
    docker:
    - image: cimg/node:16.10
    steps:
    - checkout
    - node/install-packages:
        pkg-manager: npm
    - run:
        echo "Running tests"
        npm run test
  deploy:
    docker:
    - image: cimg/node:16.10
    steps:
    - setup_remote_docker
    - heroku/install
    - checkout
    - run:
        name: Heroku Container Push
        command: |
          heroku container:login
          heroku stack:set container -a fazlieramdan-su-devops
          heroku container:push web -a fazlieramdan-su-devops
          heroku container:release web -a fazlieramdan-su-devops
  scan:
    docker:
    - image: cimg/node:16.10
    environment:
      IMAGE_NAME: fazlieramdan/education-space
    steps:
    - checkout
    - setup_remote_docker
    - docker/check
    - run: docker build -t $IMAGE_NAME .
    - synk/scan:
        docker-image-name: $IMAGE_NAME

  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: fazlieramdan/education-space
      - docker/push:
          image: fazlieramdan/education-space      


workflows:
  simple_workflow:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - test:
          requires:
            - build 
            - scan
          filters:
            branches:
              only: main   

      - scan:
        requires:
          - build  
      - build-and-push:  
          filters:
            tags:
              only: /^v.*/  
            branches: 
              ignore: /.*/
      - deploy:
          requires:
            - build-and-push
          filters:
            tags:
              only: /^v.*/
            branches: 
              ignore: /.*/
        